HealthComponent.h
UCLASS ( ClassGroup=(Custom), meta=(BlueprintSpawnableComponent) ) class TOONTANKS_API UHealthComponent float Health
Referenced by TakeDamage.
ATankGameModeBase* GameModeRef
Referenced by TakeDamage.
UHealthComponent::UHealthComponent()
virtual void BeginPlay() override
Referenced by ATankGameModeBase::BeginPlay, APawnTurret::BeginPlay, APawnTank::BeginPlay, AProjectileBase::BeginPlay.
void UHealthComponent::TakeDamage(AActor *DamageActor, float Damage, const UDamageType *DamageType, AController *InvestigatedBy, AActor *DamageCauser)
References ATankGameModeBase::ActorDied, GameModeRef, Health.