APawnBase
UCapsuleComponent * APawnBase::CapsuleComponent
Referenced by APawnBase.
UStaticMeshComponent * APawnBase::BaseMesh
Referenced by APawnBase.
UStaticMeshComponent * APawnBase::TurretMesh
Referenced by APawnBase, RotateTurret.
USceneComponent * APawnBase::ProjectileSpawnPoint
Referenced by APawnBase, Fire.
UHealthComponent * APawnBase::HealthComponent
Referenced by APawnBase.
TSubclassOf< AProjectileBase > APawnBase::ProjectileClass
Referenced by Fire.
UParticleSystem * APawnBase::DeathParticle
Referenced by HandleDestruction.
USoundBase * APawnBase::DeathSound
Referenced by HandleDestruction.
TSubclassOf< UCameraShake > APawnBase::DeathShake
Referenced by HandleDestruction.
APawnBase::APawnBase()
References BaseMesh, CapsuleComponent, HealthComponent, ProjectileSpawnPoint, TurretMesh.
void APawnBase::PawnDestroyed()
void APawnBase::HandleDestruction()
References DeathParticle, DeathShake, DeathSound.
APawnBase::APawnBase()
void APawnBase::PawnDestroyed()
virtual void APawnBase::HandleDestruction()
void APawnBase::RotateTurret(FVector LookAtTarget)
References TurretMesh.
Referenced by APawnTank::Tick.
void APawnBase::Fire()
References ProjectileClass, ProjectileSpawnPoint.
Referenced by APawnTurret::CheckFireCondition, APawnTank::SetupPlayerInputComponent.
void APawnBase::RotateTurret(FVector LookAtTarget)
void APawnBase::Fire()