APawnTurret
float APawnTurret::FireRate
Referenced by BeginPlay.
float APawnTurret::FireRange
Referenced by CheckFireCondition, Tick.
FTimerHandle APawnTurret::FireRateTimerHandle
Referenced by BeginPlay.
APawnTank * APawnTurret::PlayerPawn
Referenced by BeginPlay, CheckFireCondition, ReturnDistanceToPlayer, Tick.
void APawnTurret::CheckFireCondition()
References APawnBase::Fire, FireRange, APawnTank::GetIsPlayerAlive, PlayerPawn, ReturnDistanceToPlayer.
Referenced by BeginPlay.
float APawnTurret::ReturnDistanceToPlayer()
References PlayerPawn.
Referenced by CheckFireCondition, Tick.
void APawnTurret::CheckFireCondition()
float APawnTurret::ReturnDistanceToPlayer()
void APawnTurret::Tick(float DeltaTime) override
References FireRange, PlayerPawn, ReturnDistanceToPlayer.
void APawnTurret::HandleDestruction() override
virtual void APawnTurret::Tick(float DeltaTime) override
virtual void APawnTurret::HandleDestruction() override
void APawnTurret::BeginPlay() override
References BeginPlay, CheckFireCondition, FireRate, FireRateTimerHandle, PlayerPawn.
virtual void APawnTurret::BeginPlay() override