ATankGameModeBase
APawnTank* ATankGameModeBase::PlayerTank
Referenced by ActorDied, HandleGameStart.
int32 ATankGameModeBase::TargetTurrets
Referenced by ActorDied, HandleGameStart.
APlayerControllerBase* ATankGameModeBase::PlayerControllerRef
Referenced by ActorDied, HandleGameStart.
int32 ATankGameModeBase::StartDelay
Referenced by HandleGameStart.
int32 ATankGameModeBase::GetTargetTurretCount()
Referenced by HandleGameStart.
void ATankGameModeBase::HandleGameStart()
References GameStart, GetTargetTurretCount, PlayerControllerRef, PlayerTank, APlayerControllerBase::SetPlayerEnabledState, StartDelay, TargetTurrets.
Referenced by BeginPlay.
void ATankGameModeBase::HandleGameOver(bool PlayerWon)
References GameOver.
Referenced by ActorDied.
void ATankGameModeBase::ActorDied(AActor *DeadActor)
References APawnTank::HandleDestruction, HandleGameOver, PlayerControllerRef, PlayerTank, APlayerControllerBase::SetPlayerEnabledState, TargetTurrets.
Referenced by TakeDamage.
void ATankGameModeBase::BeginPlay() override
References BeginPlay, HandleGameStart.
void ATankGameModeBase::GameStart()
Referenced by HandleGameStart.
void ATankGameModeBase::GameOver(bool PlayerWon)
Referenced by HandleGameOver.