APawnTank
USpringArmComponent * APawnTank::SpringArm
Referenced by APawnTank.
UCameraComponent * APawnTank::Camera
Referenced by APawnTank.
FVector APawnTank::MoveDirection
Referenced by CalculateMoveInput, Move.
FQuat APawnTank::RotationDirection
Referenced by CalculateRotateInput, Rotate.
float APawnTank::MoveSpeed
Referenced by CalculateMoveInput.
float APawnTank::RotateSpeed
Referenced by CalculateRotateInput.
APlayerController * APawnTank::PlayerControllerRef
Referenced by BeginPlay, Tick.
bool APawnTank::bIsPlayerAlive
Referenced by GetIsPlayerAlive, HandleDestruction.
void APawnTank::CalculateMoveInput(float Value)
References MoveDirection, MoveSpeed.
Referenced by SetupPlayerInputComponent.
void APawnTank::CalculateRotateInput(float Value)
References RotateSpeed, RotationDirection.
Referenced by SetupPlayerInputComponent.
void APawnTank::Move()
References MoveDirection.
Referenced by Tick.
void APawnTank::Rotate()
References RotationDirection.
Referenced by Tick.
void APawnTank::CalculateMoveInput(float Value)
void APawnTank::CalculateRotateInput(float Value)
void APawnTank::Move()
void APawnTank::Rotate()
APawnTank::APawnTank()
References Camera, SpringArm.
void APawnTank::Tick(float DeltaTime) override
References Move, OUT, PlayerControllerRef, Rotate, APawnBase::RotateTurret.
void APawnTank::SetupPlayerInputComponent(class UInputComponent *PlayerInputComponent) override
References CalculateMoveInput, CalculateRotateInput, APawnBase::Fire.
void APawnTank::HandleDestruction() override
References bIsPlayerAlive.
Referenced by ATankGameModeBase::ActorDied.
bool APawnTank::GetIsPlayerAlive()
References bIsPlayerAlive.
Referenced by APawnTurret::CheckFireCondition.
APawnTank::APawnTank()
virtual void APawnTank::Tick(float DeltaTime) override
virtual void APawnTank::SetupPlayerInputComponent(class UInputComponent *PlayerInputComponent) override
virtual void APawnTank::HandleDestruction() override
bool APawnTank::GetIsPlayerAlive()
void APawnTank::BeginPlay() override
References BeginPlay, PlayerControllerRef.
virtual void APawnTank::BeginPlay() override